server:  # Server settings.
    # Address to listen on.
    addr: ":5001"
    # TLS certificate and key.
    certificate: "/ssl/docker_auth.pem"
    key: "/ssl/docker_auth.key"

token:  # Settings for the tokens.
    issuer: "Auth Service"  # Must match issuer in the Registry config.
    expiration: 900


# Static user map. 
users:
    # Password is specified as a BCrypt hash.
    # htpasswd -B -n
    "admin":
        password: "$2y$05$VoMk1htKkwxXQLLgWfIIQuCyQksdGZ61QU4cuTOThYgCDPZMffqfy"
    "": {}  # Allow anonymous (no "docker login") access.

acl:
    # Admin has full access to everything.
    - match: {account: "admin"}
        actions: ["*"]
    # All logged in users can pull all images.
    - match: {account: "/.+/"}
        actions: ["pull"]
    # Anonymous users can pull "hello-world".
    - match: {account: "", name: "hello-world"}
        actions: ["pull"]
    # Access is denied by default.