# Create all the machines and docker containers needed to run the SafeHarbor server.
# This includes the Cesanta authorization server.
# Note: This vagrantfile depends on the env variables defined in safeharbor.conf

# Standard settings - these should not need to change.
@CesantaServerName = "docker_auth"
@SafeHarborDir = "/home/vagrant/safeharbor"
@SafeHarborServerName = "SafeHarbor"
@SafeHarborExecutable = "SafeHarborServer"

# Variables set by the environment.
@vmboxname = ENV['vmboxname']
@vmboxurl = ENV['vmboxurl']
@CesantaPort = ENV['CesantaPort']
@CesantaConfDir = ENV['CesantaConfDir']
@CesantaSSLDir = ENV['CesantaSSLDir']
@CesantaDockerImage = ENV['CesantaDockerImage']
@SafeHarborPort = ENV['SafeHarborPort']
@SafeHarborConfPath = ENV['SafeHarborConfPath']
@SafeHarborDockerImage = ENV['SafeHarborDockerImage']
@SafeHarborPackageName = ENV['SafeHarborPackageName']

# Derived - do not change.
@LocalPrivateKeyPath = "#{@CesantaServerName}.key"
@LocalPemPath = "#{@CesantaServerName}.pem"
@LocalCertPath = "#{@CesantaServerName}.crt"

Vagrant.configure(2) do |config|

	# Configure the OS.
	config.vm.box = "centos/7"
	#config.vm.box = @vmboxname
	#config.vm.box_url = @vmboxurl
	config.vm.hostname = "SafeHarborServer"
	config.vm.network "private_network", ip: "192.168.100.10", virtualbox__intnet: "safeharbor"
	config.vm.network "forwarded_port", guest: @CesantaPort, host: @CesantaPort
	config.vm.network "forwarded_port", guest: @SafeHarborPort, host: @SafeHarborPort
	
	# Create directories needed for installing Cesanta.
	config.vm.provision "shell", inline: <<-SHELL
		if ! [ -d #{@CesantaConfDir} ]; then mkdir -p #{@CesantaConfDir}; fi
		if ! [ -d #{@CesantaSSLDir} ]; then mkdir -p #{@CesantaSSLDir}; fi
		sudo chown vagrant:vagrant #{@CesantaConfDir}
		sudo chown vagrant:vagrant #{@CesantaSSLDir}
	SHELL

	# Copy the Cesanta configuration file and credentials to the VM.
	config.vm.provision "file", source: "auth_config.yml", destination: "#{@CesantaConfDir}/auth_config.yml"
	config.vm.provision "file", source: @LocalPrivateKeyPath, destination: "#{@CesantaSSLDir}/#{@CesantaServerName}.key"
	#config.vm.provision "file", source: @LocalPemPath, destination: "#{@CesantaSSLDir}/#{@CesantaServerName}.pem"
	
	# Create directories needed for installing SafeHarbor.
	config.vm.provision "shell", inline: <<-SHELL
		if ! [ -d #{@SafeHarborDir} ]; then mkdir -p #{@SafeHarborDir}; fi
		sudo chown vagrant:vagrant #{@SafeHarborDir}
	SHELL
	
	# Obtain the SafeHarbor installation package.
	config.vm.provision "file", source: @SafeHarborPackageName, destination: @SafeHarborDir
	
	# Prepare a directory from which SafeHarborServer can be run. This directory
	# will be mapped to the docker containers.
	config.vm.provision "shell", inline: <<-SHELL
		sudo yum install -y unzip
		cd safeharbor; unzip -o -q safeharbor
		cp /vagrant/*.json /home/vagrant/safeharbor
		cp /vagrant/*.key /home/vagrant/safeharbor
		cp /vagrant/*.crt /home/vagrant/safeharbor
		cp /vagrant/*.yml /home/vagrant/safeharbor
		mkdir /home/vagrant/safeharbor/Repositories
		sudo chown vagrant:vagrant /home/vagrant/safeharbor/*
		sudo chown vagrant:vagrant /home/vagrant/safeharbor/Repositories
	SHELL

	# Install patch needed by RHEL7/Centos7 to make the vagrant docker provisioner work.
	config.vm.provision "shell", inline: <<-SHELL
		#yum-config-manager --enable ol7_addons
		groupadd docker
		usermod -a -G docker vagrant
	SHELL

	# Install docker and run the images for Cesanta and SafeHarbor.
	config.vm.provision "docker" do |d|
		
		# Obtain the Cesanta docker image
		d.pull_images @CesantaDockerImage
		
		# Install the SafeHarborServer.
		d.pull_images @SafeHarborDockerImage
	end

end
