server:  # Auth server (Cesanta) settings.
  # Address to listen on.
  addr: ":5001"
  # TLS certificate and key.
  certificate: "/ssl/docker_auth.pem"
  key: "/ssl/docker_auth.key"

token:  # Settings for the tokens.
  issuer: "Auth Service"  # Must match issuer in the Registry config.
  expiration: 900

# Static user map. 
users:
  # Password is specified as a BCrypt hash.
  # htpasswd -B -n
  "admin":
    password: "$2y$05$VoMk1htKkwxXQLLgWfIIQuCyQksdGZ61QU4cuTOThYgCDPZMffqfy"
  "": {}  # Allow anonymous (no "docker login") access.

acl:
  # account -> account
  # type -> 
  # name -> scope
  #
  # E.g.,
  # scope="repository:husseingalal/hello:push"
  #        type      :name              :actions
  # Admin has full access to everything.
  - match: {account: "admin", type: "repository", name: "*"}
    actions: ["push,create-user"]
  # Access is denied by default.