# Deploy SafeHarborServer and all of its components, using Docker Compose.
version: '2'
services:
  shs:
    container_name: safeharborserver
    depends_on:
      - redis
      - clair
      - registry
    image: ${SafeHarborImageName}
    #network_mode: "host"
    ports:
      - ${SafeHarborPort}:${SafeHarborPort}
    volumes:
      - ${DataVolMountPoint}:/safeharbor/data
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - redis

  redis:
    image: docker.io/redis
    command: redis-server --appendonly yes /config/redis.conf
    volumes:
      - /home/centos/SafeHarborServer/build/Centos7:/config
      - /home/centos/safeharbordata:/data
    #network_mode: "host"

  clair:
    container_name: clair
    depends_on:
      - postgres
    image: quay.io/coreos/clair-git:latest
    #image: quay.io/coreos/clair
    restart: unless-stopped
    ports:
      - "6060-6061:6060-6061"
    command: [-config, /config/clairconfig.yaml
    #command: --config=/config/clairconfig.yaml
    #network_mode: "host"
    links:
      - postgres
    volumes:
      - /tmp:/tmp
      - /home/centos/SafeHarborServer/deploy/Compose:/config:ro

  registry:
    image: docker.io/registry:2
    #network_mode: "host"
    ports:
      - ${RegistryPort}:${RegistryPort}
    volumes:
      - ${DataVolMountPoint}/registryauth:/auth
      - ${DataVolMountPoint}/registrydata:/var/lib/registry
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    #network_mode: "host"
    environment:
      POSTGRES_PASSWORD: ${postgresPassword}
