apiVersion: v1
kind: Service
metadata:
  name: safeharborserver
  labels:
    app: safeharborserver
spec:
  type: NodePort  # One of ClusterIP, NodePort, or LoadBalancer. Defaults to ClusterIP.
  ports:
  - port: 80
    name: http
    targetPort: 80
    protocol: TCP
  selector:
    app: safeharborserver
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: safeharborserver
spec:
  replicas: 1
  template: # See https://blog.redspread.com/2016/02/09/Using-AWS-EC2-Container-Registry-with-K8S/
    metadata:
      labels:
        app: safeharborserver
    spec:
      imagePullSecrets:
        - name: scaledmarkets_registrykey
      containers:
      - name: safeharborserver
        image: 5000-5857-3678.dkr.ecr.us-east-1.amazonaws.com/safeharborserver:latest  
        ports:
        - containerPort: 80
