apiVersion: v1
kind: Service
metadata:
  name: safeharborserver
  labels:
    app: safeharborserver
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80 # 6000
      protocol: TCP
  selector:
    app: safeharborserver
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: safeharborserver
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: safeharborserver
    spec:
      imagePullSecrets:
        - name: scaledmarkets_registrykey
      containers:
        - name: safeharborserver
          image: nginx # 5000-5857-3678.dkr.ecr.us-east-1.amazonaws.com/safeharborserver:latest
          ports:
            - containerPort: 80 #6000
